-- Mock Bank App — base schema.
-- FROZEN: columns/types here are the shared contract for both verticals.
-- Do not alter columns in a feature branch.

CREATE TABLE customers (
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name   VARCHAR(120) NOT NULL,
    status VARCHAR(20)  NOT NULL DEFAULT 'active'
        CONSTRAINT ck_customers_status CHECK (status IN ('active', 'frozen'))
);

CREATE TABLE accounts (
    id              BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id     BIGINT         NOT NULL,
    balance         NUMERIC(14, 2) NOT NULL DEFAULT 0,
    hold            BOOLEAN        NOT NULL DEFAULT FALSE,
    daily_withdrawn NUMERIC(14, 2) NOT NULL DEFAULT 0,
    status          VARCHAR(20)    NOT NULL DEFAULT 'active',
    CONSTRAINT fk_accounts_customer FOREIGN KEY (customer_id) REFERENCES customers (id)
);

CREATE TABLE recipients (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT       NOT NULL,
    name        VARCHAR(120) NOT NULL,
    enrolled    BOOLEAN      NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_recipients_customer FOREIGN KEY (customer_id) REFERENCES customers (id)
);

CREATE TABLE transactions (
    id         BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT         NOT NULL,
    type       VARCHAR(20)    NOT NULL
        CONSTRAINT ck_transactions_type CHECK (type IN ('transfer', 'withdraw', 'billpay')),
    amount     NUMERIC(14, 2) NOT NULL,
    status     VARCHAR(20)    NOT NULL
        CONSTRAINT ck_transactions_status CHECK (status IN ('completed', 'pending', 'failed')),
    created_at TIMESTAMP      NOT NULL DEFAULT now(),
    CONSTRAINT fk_transactions_account FOREIGN KEY (account_id) REFERENCES accounts (id)
);

CREATE TABLE scheduled_payments (
    id         BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT         NOT NULL,
    payee      VARCHAR(120)   NOT NULL,
    amount     NUMERIC(14, 2) NOT NULL,
    fire_date  DATE           NOT NULL,
    status     VARCHAR(20)    NOT NULL
        CONSTRAINT ck_scheduled_payments_status CHECK (status IN ('scheduled', 'pending', 'paid', 'failed')),
    CONSTRAINT fk_scheduled_payments_account FOREIGN KEY (account_id) REFERENCES accounts (id)
);

CREATE TABLE approvals (
    id           BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transfer_ref VARCHAR(64)    NOT NULL,
    amount       NUMERIC(14, 2) NOT NULL,
    status       VARCHAR(20)    NOT NULL DEFAULT 'pending'
        CONSTRAINT ck_approvals_status CHECK (status IN ('pending', 'approved', 'rejected')),
    created_at   TIMESTAMP      NOT NULL DEFAULT now()
);

CREATE INDEX idx_accounts_customer_id           ON accounts (customer_id);
CREATE INDEX idx_recipients_customer_id         ON recipients (customer_id);
CREATE INDEX idx_transactions_account_id        ON transactions (account_id);
CREATE INDEX idx_scheduled_payments_account_id  ON scheduled_payments (account_id);
CREATE INDEX idx_approvals_transfer_ref         ON approvals (transfer_ref);
